name = "timetravel"
version = "0.2.2"
target = "javascript"

description = "Development-only time travel and state inspection for Lustre applications"
licences = ["MIT"]
repository = { type = "github", user = "bmehder", repo = "timetravel" }
links = [{ title = "GitHub", href = "https://github.com/bmehder/timetravel" }]

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
lustre = ">= 5.7.1 and < 6.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
